export const FETCH_ARTIFACTS = 'FETCH_ARTIFACTS';
export const CREATE_ARTIFACT = 'CREATE_ARTIFACT';
export const EDIT_ARTIFACT = 'EDIT_ARTIFACT';
export const DELETE_ARTIFACT = 'DELETE_ARTIFACT';
export const FETCH_ARTIFACT = 'FETCH_ARTIFACT';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const FETCH_USER = 'FETCH_USER';
export const CREATE_FAMILY = 'CREATE_FAMILY';
